spring:    
  datasource:
    url: jdbc:mysql://localhost:3306/drone
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    
    properties:
      hibernate:
        dialect:org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
